#!/usr/bin/env python
#File to mimic the interface of command node, so that we dont need robot on to code and test code.

# TO DO --> Add time (rospy.get_time()), add velocity check

#------------------------------------------------------------------------ IMPORTS

import rospy
import time
from musi_care.srv import qt_command
#from qt_robot_interface.srv import * #so we can use the qt service srvs
#from qt_gesture_controller.srv import * # #so we can use the service srv "gesture_play" 
from qt_motors_controller.srv import *
from std_msgs.msg import String #so we can become a publisher and publish a string to the QT node that handles tts.
from std_msgs.msg import Bool
from sensor_msgs.msg import JointState
rospy.init_node('speak')

# ---------------------------------------------------------------------- VARIABLES

# ----- Variables for joints position
r_s_pitch_pos = 0
r_s_roll_pos = 0
r_e_roll_pos = 0
l_s_pitch_pos = 0
l_s_roll_pos = 0
l_e_roll_pos = 0

# ----- Variables for joints velocity
r_s_pitch_vel = 0
r_s_roll_vel = 0
r_e_roll_vel = 0
l_s__pitch_vel = 0
l_s__roll_vel = 0
l_e_roll_vel = 0

# ----- Variables for joints effort
r_s_pitch_eff = 0
r_s_roll_eff = 0
r_e_roll_eff = 0
l_s__pitch_eff = 0
l_s__roll_eff = 0
l_e_roll_eff = 0

#right_j_vel = [r_s_pitch_vel, r_s_roll_vel, r_e_roll_vel]
#left_j_vel = [l_s__pitch_vel, l_s__roll_vel, l_e_roll_vel]

# --------------------------------------------------------------------- FUNCTIONS

# ---------- To obtain position of joints

def state_callback(msg):
    global r_s_pitch_pos
    global r_s_roll_pos
    global r_e_roll_pos
    global l_s_pitch_pos
    global l_s_roll_pos
    global l_e_roll_pos
    
    # Right Arm Joints
    r_s_pitch_pos = msg.position[msg.name.index("RightShoulderPitch")]
    r_s_roll_pos = msg.position[msg.name.index("RightShoulderRoll")]
    r_e_roll_pos = msg.position[msg.name.index("RightElbowRoll")]
    
    # Left Arm Joints
    l_s_pitch_pos = msg.position[msg.name.index("LeftShoulderPitch")]
    l_s_roll_pos = msg.position[msg.name.index("LeftShoulderRoll")]
    l_e_roll_pos = msg.position[msg.name.index("LeftElbowRoll")]
    


rospy.Subscriber('/qt_robot/joints/state', JointState, state_callback)

# ------------------- Obtain VELOCTY

def vel_msg(msg):
    global r_s_pitch_vel
    global r_s_roll_vel
    global r_e_roll_vel
    global l_s__pitch_vel
    global l_s__roll_vel
    global l_e_roll_vel
    
    # Right Arm motor velocity
    r_s_pitch_vel = msg.velocity[msg.name.index("RightShoulderPitch")]
    r_s_roll_vel = msg.velocity[msg.name.index("RightShoulderRoll")]
    r_e_roll_vel = msg.velocity[msg.name.index("RightElbowRoll")]
    
    # Left Arm motor velocity
    l_s__pitch_vel = msg.velocity[msg.name.index("LeftShoulderPitch")]
    l_s__roll_vel = msg.velocity[msg.name.index("LeftShoulderRoll")]
    l_e_roll_vel = msg.velocity[msg.name.index("LeftElbowRoll")]
    
rospy.Subscriber('/qt_robot/joints/state', JointState, vel_msg)

# --------------------- Obtain EFFORT messages

def effort_msg(msg):
    global r_s_pitch_eff
    global r_s_roll_eff
    global r_e_roll_eff
    global l_s__pitch_eff
    global l_s__roll_eff
    global l_e_roll_eff
    
    # Right Arm motor velocity
    r_s_pitch_eff = msg.effort[msg.name.index("RightShoulderPitch")]
    r_s_roll_eff = msg.effort[msg.name.index("RightShoulderRoll")]
    r_e_roll_eff = msg.effort[msg.name.index("RightElbowRoll")]
    
    # Left Arm motor velocity
    l_s__pitch_eff = msg.effort[msg.name.index("LeftShoulderPitch")]
    l_s__roll_eff = msg.effort[msg.name.index("LeftShoulderRoll")]
    l_e_roll_eff = msg.effort[msg.name.index("LeftElbowRoll")]
    
rospy.Subscriber('/qt_robot/joints/state', JointState, effort_msg)

# ---------- To check if motors reached desired position
        
def check_pos(position, target):
    my_target = target.replace('"', "")
    my_target = my_target.replace(',', "")
    my_target = my_target.replace('[', "")
    my_target = my_target.replace(']', "")
    my_target = my_target.split()
    s_pitch, s_roll, e_roll = float(my_target[0]), float(my_target[1]), float(my_target[1])
    target_reached = False
    while not target_reached:
        target_reached = (round(s_pitch, 2) == round(position[0], 2)) and (round(s_roll, 2) == round(position[1], 2)) and (round(e_roll, 2) == round(position[2], 2))
    return True
    
# ---------- To move arms closer to the xylophone (to avoid hitting the holder with the mallets)

# ---------- To change the speed of the motors

def change_mot_speed(speed_percent):
	action_type = "velocity"
	action_content = speed_percent
	command_blocking = False

	rospy.wait_for_service('/qt_command_service')
	command_controller = rospy.ServiceProxy('/qt_command_service', qt_command)
	#command_complete = command_controller(action_type, action_content, command_blocking)

	#print(command_complete)


def get_ready(arm, move_1, move_2, move_3):

	print("----- GET READY -----")
	start = rospy.get_time() # ---- Start Timing
	action_type = arm
	action_content = move_1
	command_blocking = False

	rospy.wait_for_service('/qt_command_service')
	command_controller = rospy.ServiceProxy('/qt_command_service', qt_command)
	command_complete = command_controller(action_type, action_content, command_blocking)
	rospy.sleep(0.1)

	print(command_complete)
	finish = rospy.get_time() # ----- Stop Timing
	elapsed = round((finish - start), 3) # ----- Calculate Time Elapsed
	print(elapsed, "   Sec.")
	print("----------", action_type, "----------")
	print("DESIRED POS:	", action_content)
	if action_type == "right_arm":
	    actual_pos = [r_s_pitch_pos, r_s_roll_pos, r_e_roll_pos]
	    '''ac_list = action_content.replace('"', "")
	    ac_list = ac_list.replace(',', "")
	    ac_list = ac_list.replace('[', "")
	    ac_list = ac_list.replace(']', "")
	    print("modified: ", ac_list)
	    ac_list = ac_list.split()
	    #print(ac_list)
	    #print(type(ac_list))
	    #print(ac_list[0])
	    #print(type(ac_list[0]))'''
	    #check_pos(actual_pos,  action_content)
	    print("REAL POS:	", actual_pos)
	else:
	    actual_pos = [l_s_pitch_pos, l_s_roll_pos, l_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	    
	#rospy.sleep(0.1)
	
	# ------------------------------------------------------------------------
	start = rospy.get_time() # ----- Start Timing
	action_type = arm
	action_content = move_2
	command_blocking = False

	rospy.wait_for_service('/qt_command_service')
	command_controller = rospy.ServiceProxy('/qt_command_service', qt_command)
	command_complete = command_controller(action_type, action_content, command_blocking)
	rospy.sleep(0.1)
	print(command_complete)
	finish = rospy.get_time() # ----- Stop Timing
	elapsed = round((finish - start), 3) # ----- Calculate Time Elapsed
	print(elapsed, "   Sec.")
	print("----------", action_type, "----------")
	print("DESIRED POS:	", action_content)
	if action_type == "right_arm":
	    actual_pos = [r_s_pitch_pos, r_s_roll_pos, r_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	else:
	    actual_pos = [l_s_pitch_pos, l_s_roll_pos, l_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	    
	#rospy.sleep(0.1)
	
	# ------------------------------------------------------------------------
	start = rospy.get_time() # ----- Start Timing
	action_type = arm
	action_content = move_3
	command_blocking = False

	rospy.wait_for_service('/qt_command_service')
	command_controller = rospy.ServiceProxy('/qt_command_service', qt_command)
	command_complete = command_controller(action_type, action_content, command_blocking)
	rospy.sleep(0.1)
	print(command_complete)
	finish = rospy.get_time() # ----- Stop Timing
	elapsed = round((finish - start), 3) # ----- Calculate Time Elapsed
	print(elapsed, "   Sec.")
	print("----------", action_type, "----------")
	print("DESIRED POS:	", action_content)
	if action_type == "right_arm":
	    actual_pos = [r_s_pitch_pos, r_s_roll_pos, r_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	else:
	    actual_pos = [l_s_pitch_pos, l_s_roll_pos, l_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	    
	#rospy.sleep(3)

# ---------- Function to play a note (now same function for right/left arm)

def play_note(arm, key, offset):
	
	print("----- PLAY NOTE -----")
	#actual_pos = [r_s_pitch_pos, r_s_roll_pos, r_e_roll_pos]
        # ---------- OFFSET
	start = rospy.get_time() # ----- Start Timing
	action_type = arm
	action_content = offset
	command_blocking = False

	rospy.wait_for_service('/qt_command_service')
	command_controller = rospy.ServiceProxy('/qt_command_service', qt_command)
	command_complete = command_controller(action_type, action_content, command_blocking)
	rospy.sleep(0.1)
	
	#check_pos(actual_pos,  action_content)
	print(command_complete)
	finish = rospy.get_time() # ----- Stop Timing
	elapsed = round((finish - start), 3) # ----- Calculate Time Elapsed
	print(elapsed, "   Sec.")
	print("----------", action_type, "----------")
	print("DESIRED POS:	", action_content)
	if action_type == "right_arm":
	    actual_pos = [r_s_pitch_pos, r_s_roll_pos, r_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	    #print("RIGHT_S_PITCH:	", r_s_pitch_pos)
	    #print("RIGHT_S_ROLL:	", r_s_roll_pos)
	    #print("RIGHT_E_ROLL:	", r_e_roll_pos)
	else:
	    actual_pos = [l_s_pitch_pos, l_s_roll_pos, l_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	    #print("LEFT_S_PITCH:	", l_s_pitch_pos)
	    #print("LEFT_S_ROLL:	", l_s_roll_pos)
	    #print("LEFT_E_ROLL:	", l_e_roll_pos)
	    
	#rospy.sleep(2)
	
	# ---------- NOTE
	start = rospy.get_time() # ----- Start Timing
	action_type = arm
	action_content = key
	command_blocking = False

	rospy.wait_for_service('/qt_command_service')
	command_controller = rospy.ServiceProxy('/qt_command_service', qt_command)
	command_complete = command_controller(action_type, action_content, command_blocking)
	rospy.sleep(0.1)
	#check_pos(actual_pos,  action_content)
	print(command_complete)
	finish = rospy.get_time() # ----- Stop Timing
	elapsed = round((finish - start), 3) # ----- Calculate Time Elapsed
	print(elapsed, "   Sec.")
	print("----------", action_type, "----------")
	print("DESIRED POS:	", action_content)
	if action_type == "right_arm":
	    actual_pos = [r_s_pitch_pos, r_s_roll_pos, r_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	else:
	    actual_pos = [l_s_pitch_pos, l_s_roll_pos, l_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	
	#rospy.sleep(2)
	# ---------- OFFSET 
	start = rospy.get_time() # ----- Start Timing
	action_type = arm
	action_content = offset
	command_blocking = False

	rospy.wait_for_service('/qt_command_service')
	command_controller = rospy.ServiceProxy('/qt_command_service', qt_command)
	command_complete = command_controller(action_type, action_content, command_blocking)
	rospy.sleep(0.1)
        
	#check_pos(actual_pos,  action_content)
	#check_pos(actual_pos, offset)
	finish = rospy.get_time() # ----- Stop Timing
	elapsed = round((finish - start), 3) # ----- Calculate Time Elapsed
	print(elapsed, "   Sec.")
	print(command_complete)
	print("----------", action_type, "----------")
	print("DESIRED POS:	", action_content)
	if action_type == "right_arm":
	    actual_pos = [r_s_pitch_pos, r_s_roll_pos, r_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	else:
	    actual_pos = [l_s_pitch_pos, l_s_roll_pos, l_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	    
	#rospy.sleep(2)

# ----- home to test
def go_home(arm, pose):
	start = rospy.get_time() # ----- Start Timing
	action_type = arm
	action_content = pose
	command_blocking = False

	rospy.wait_for_service('/qt_command_service')
	command_controller = rospy.ServiceProxy('/qt_command_service', qt_command)
	command_complete = command_controller(action_type, action_content, command_blocking)
	rospy.sleep(0.1)
	print(command_complete)
	finish = rospy.get_time() # ----- Stop Timing
	elapsed = round((finish - start), 3) # ----- Calculate Time Elapsed
	print(elapsed, "   Sec.")
	print("----------", action_type, "----------")
	print("DESIRED POS:	", action_content)
	if action_type == "right_arm":
	    actual_pos = [r_s_pitch_pos, r_s_roll_pos, r_e_roll_pos]
	    print("REAL POS:	", actual_pos)
	else:
	    actual_pos = [l_s_pitch_pos, l_s_roll_pos, l_e_roll_pos]
	    print("REAL POS:	", actual_pos)


#---------------------------------------- ANGLES READNG TO HIT KEYS

Home = "[0, 0, 0]" #[-87.0, -86.30000305175781, -7.400000095367432]


#---------------------------------------- RIGHT ARM ----------------------------------------
# ------------------- Sending right arm to 'Get Ready' position
r_pose1 = "[-81.0999984741211, -16.600000381469727, -34.5]"

r_pose2 = "[35.5, -12.0, -34.5]"

r_pose3 = "[29.899999618530273, -48.20000076293945, -35.20000076293945]"
# ------------------------

offset_C_FI = "[17.099999904632568, -43.0, -56.0]"
C_FI = "[7.099999904632568, -43.0, -56.0]"

offset_B = "[17.099999904632568, -53.400001525878906, -50.79999923706055]"
B = "[7.099999904632568, -53.400001525878906, -50.79999923706055]"

offset_A = "[16.800000190734863, -66.0999984741211, -42.70000076293945]"
A = "[6.800000190734863, -66.0999984741211, -42.70000076293945]"

offset_G = "[16.800000190734863, -78.80000305175781, -33.900001525878906]"
G = "[6.800000190734863, -78.80000305175781, -33.900001525878906]"

# ---------------------------------------- LEFT ARM ----------------------------------------
# ------------------- Sending left arm to 'Get Ready' position
l_pose1 = "[81.0999984741211, -16.600000381469727, -34.5]"

l_pose2 = "[-35.5, -12.0, -34.5]"

l_pose3 = "[-29.899999618530273, -48.20000076293945, -35.20000076293945]"
# ------------------------
'''
offset_C_R = "[-31.699999809265137, -41.0, -57.0]"
C_R = "[-11.699999809265137, -41.0, -57.0]"
offset_D = "[-31.0, -51.79999923706055, -51.79999923706055]"
D = "[-11.0, -51.79999923706055, -51.79999923706055]"
offset_E = "[-31.0, -64.80000305175781, -44.0]"
E = "[-11.0, -64.80000305175781, -44.0]"
offset_F = "[-31.0, -75.9000015258789, -37.099998474121094]"
F = "[-11.0, -75.9000015258789, -37.099998474121094]"'''

#new ones
offset_C_R = "[-21.699999809265137, -45.599998474121094, -48.900001525878906]"
C_R = "[-11.699999809265137, -45.599998474121094, -48.900001525878906]"
offset_D = "[-21.699999809265137, -52.099998474121094, -48.900001525878906]"
D = "[-11.699999809265137, -52.099998474121094, -48.900001525878906]"
offset_E = "[-21.399999618530273, -63.79999923706055, -42.0]"
E = "[-11.399999618530273, -63.79999923706055, -42.0]"
offset_F = "[-21.0, -74.30000305175781, -37.400001525878906]"
F = "[-11.0, -74.30000305175781, -37.400001525878906]"

#--------------------------------------------------------------------------------
#get_ready("right_arm", r_pose1, r_pose2, r_pose3)
#get_ready("left_arm",  l_pose1, l_pose2, l_pose3)

# -------------------------- TESTING ACCURACY WITH DIFFERENT SPEEDS (MULTIPLE ITERATIONS)
print("SPEED AT 50")
start = rospy.get_time()
change_mot_speed("50")
play_note("right_arm", C_FI, offset_C_FI)
play_note("right_arm", B, offset_B)
play_note("right_arm", A, offset_A)
play_note("right_arm", G, offset_G)

change_mot_speed("50")
play_note("left_arm", C_R, offset_C_R)
play_note("left_arm", D, offset_D)
play_note("left_arm", E, offset_E)
play_note("left_arm", F, offset_F)
finish = rospy.get_time()
elapsed = round((finish - start), 3)
print("TIME TO PLAY ALL KEYS:    ", elapsed, "   Sec.")

'''
print("SPEED AT 100")
start = rospy.get_time()

change_mot_speed("100")
play_note("right_arm", C_FI, offset_C_FI)
play_note("right_arm", B, offset_B)
play_note("right_arm", A, offset_A)
play_note("right_arm", G, offset_G)


change_mot_speed("100")
play_note("left_arm", C_R, offset_C_R)
play_note("left_arm", D, offset_D)
play_note("left_arm", E, offset_E)
play_note("left_arm", F, offset_F)'''

finish = rospy.get_time()
elapsed = round((finish - start), 3)
print("TIME TO PLAY ALL KEYS:    ", elapsed, "   Sec.")
'''
change_mot_speed("50")
print("---------- MOTOR SPEED AT 50 ----------")
for i in range (2):
    #go_home("right_arm", Home)
    play_note("right_arm", B, offset_B)
    
rospy.sleep(3)
go_home("right_arm", Home)
change_mot_speed("100")
print("---------- MOTOR SPEED AT 100 ----------")
for i in range (2):
    #go_home("right_arm", Home)
    play_note("right_arm", B, offset_B)
'''
# -------------------------- ---------------------------
#TEST = "[17.200000762939453, -41.0, -31.200000762939453]"
#OFF_T = "[22.200000762939453, -41.0, -31.200000762939453]"


# ----------------------------------~~ for tests
#go_home("right_arm", Home)
#go_home("left_arm", Home)
# ----------------------------------------------------
'''
for i in range(10):
    print("-------------  ", i, " LOOP  -------------")
    play_note("right_arm", C_FI, offset_C_FI)
    #play_note("right_arm", B, offset_B)
    #play_note("right_arm", A, offset_A)
    #play_note("right_arm", G, offset_G)'''

'''for i in range(10):
    play_note("right_arm", B, offset_B)'''
#play_note("right_arm", B, offset_B)
#play_note("right_arm", A, offset_A)

