#!/usr/bin/env python
#File to mimic the interface of command node, so that we dont need robot on to code and test code.

# TO DO --> Add time (rospy.get_time()), add velocity check

#------------------------------------------------------------------------ IMPORTS

import rospy
import time
from musi_care.srv import qt_command
#from qt_robot_interface.srv import * #so we can use the qt service srvs
#from qt_gesture_controller.srv import * # #so we can use the service srv "gesture_play" 
from qt_motors_controller.srv import *
from std_msgs.msg import String #so we can become a publisher and publish a string to the QT node that handles tts.
from std_msgs.msg import Bool
from sensor_msgs.msg import JointState
from Class_Lib import QT_Controller
rospy.init_node('QT_Xylophone')

qt_xy = QT_Controller()
#---------------------------------------- ANGLES READNG TO HIT KEYS

Home = "[0, 0, 0]" #[-87.0, -86.30000305175781, -7.400000095367432]


#---------------------------------------- RIGHT ARM ----------------------------------------
# ------------------- Sending right arm to 'Get Ready' position
r_pose1 = "[-81.0999984741211, -16.600000381469727, -34.5]"

r_pose2 = "[35.5, -12.0, -34.5]"

r_pose3 = "[29.899999618530273, -48.20000076293945, -35.20000076293945]"
# ------------------------



# ---------------------------------------- LEFT ARM ----------------------------------------
# ------------------- Sending left arm to 'Get Ready' position
l_pose1 = "[81.0999984741211, -16.600000381469727, -34.5]"

l_pose2 = "[-35.5, -12.0, -34.5]"

l_pose3 = "[-29.899999618530273, -48.20000076293945, -35.20000076293945]"
# ------------------------

offset_C_First_Inv = "[27.600000381469727, -51.5, -43.29999923706055]" #55
C_First_Inv = "[17.600000381469727, -51.5, -43.29999923706055]"
offset_B = "[26.299999237060547, -59.0, -42.70000076293945]" # 54
B = "[16.299999237060547, -59.0, -42.70000076293945]"
offset_A = "[25.300000190734863, -75.9000015258789, -28.0]" #46
A = "[15.300000190734863, -75.9000015258789, -28.0]"
offset_G = "[25.899999618530273, -84.4000015258789, -25.100000381469727]" #38
G = "[15.899999618530273, -84.4000015258789, -25.100000381469727]"
offset_C_ROOT = "[-34.100000381469727, -37.79999923706055, -58.29999923706055]" #62
C_ROOT = "[-24.100000381469727, -37.79999923706055, -58.29999923706055]"
offset_D = "[-34.399999618530273, -44.0, -58.29999923706055]" #58
D = "[-24.399999618530273, -44.0, -58.29999923706055]"
offset_E = "[-35.100000381469727, -52.099998474121094, -58.599998474121094]" # 53
E = "[-25.100000381469727, -52.099998474121094, -58.599998474121094]"
offset_F = "[-33.399999618530273, -66.0999984741211, -47.900001525878906] " # 43
F = "[-23.399999618530273, -66.0999984741211, -47.900001525878906] "

#--------------------------------------------------------------------------------
#get_ready("right_arm", r_pose1, r_pose2, r_pose3)
#get_ready("left_arm",  l_pose1, l_pose2, l_pose3)

# -------------------------- TESTING ACCURACY WITH DIFFERENT SPEEDS RIGHT ARM

# 25% DONE ||
change_mot_speed("100") #50 # 75 #100

qt_xy.play_note("right_arm", C_First_Inv, offset_C_First_Inv)
qt_xy.play_note("right_arm", B, offset_B)
qt_xy.play_note("right_arm", A, offset_A)
qt_xy.play_note("right_arm", G, offset_G)
'''
# -------------------------------------------------------------
# 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
change_mot_speed("25") #50 # 75 #100
get_ready("right_arm", r_pose1, r_pose2, r_pose3)
get_ready("left_arm",  l_pose1, l_pose2, l_pose3)


play_note("right_arm", C_FI, offset_C_FI)
play_note("right_arm", B, offset_B)
play_note("right_arm", A, offset_A)
play_note("right_arm", G, offset_G)
'''
# -----------------------------------------------------------

'''
for i in range(3):
    print(i, "ITERATION")
    change_mot_speed("25") #50 # 75 #100
    play_note("right_arm", C_FI, offset_C_FI)
    play_note("right_arm", B, offset_B)
    play_note("right_arm", A, offset_A)
    play_note("right_arm", G, offset_G)
'''
# -----------------------------------------------------------
'''
for i in range(3):
    print(i, "ITERATION")
    change_mot_speed("25") #50 # 75 #100
    get_ready("right_arm", r_pose1, r_pose2, r_pose3)
    get_ready("left_arm",  l_pose1, l_pose2, l_pose3)
    play_note("right_arm", C_FI, offset_C_FI)
    play_note("right_arm", B, offset_B)
    play_note("right_arm", A, offset_A)
    play_note("right_arm", G, offset_G)
'''
'''
for i in range(5):
    change_mot_speed("25") # 50 # 75 # 100
    play_note("right_arm", G, offset_G)
    
'''
'''
for i in range(5):
    change_mot_speed("25") # 50 # 75 # 100
    play_note("right_arm", A, offset_A)
'''
'''
for i in range(5):
    change_mot_speed("25") # 50 # 75 # 100
    play_note("right_arm", B, offset_B)
    
'''
'''
for i in range(5):
    change_mot_speed("25") # 50 # 75 # 100
    play_note("right_arm", C_FI, offset_C_FI)
    
'''
    
'''
change_mot_speed("25") #50 # 75 #100
play_note("right_arm", C_FI, offset_C_FI)
'''
'''
change_mot_speed("25") #50 # 75 #100
play_note("right_arm", G, offset_G)
'''
'''
change_mot_speed("25") #50 # 75 #100
play_note("right_arm", A, offset_A)
'''
'''
change_mot_speed("25") #50 # 75 #100
play_note("right_arm", B, offset_B)
'''
